<?php
return [
    'enable' => array(
        "MasterHr",
        "MasterSales",
        "CloudTelephony",
        "BlockStages",
        "BmsLists",
        "PropertyPortals",
        "WebsiteSettings",
        "AssignWebEnquiries",
        "BloodGroups",
        "EnquirySource",
        "PaymentHeadings",
        "ManageStates",
        "ManageCountry",
        "ManageCity",
        "ManageLocation",
        "HighestEducation",
        "DiscountHeadings",
        "ManageDepartment",
        "ManageProfession",
        "ManageProjectTypes",
        "ManageLostReason",
        "ManageProjectTypes",
        "ManageBlockTypes",
        "ProjectPaymentStages",
        "ContactUs",
        "WebPages",
        "BlogManagement",
        "Testimonials",
<<<<<<< HEAD
        "EmailConfig",
        "CareerManagement",
        "DashBoard",
=======
        "CareerManagement",
        "DashBoard",
        "EmailConfig",
        "CareerManagement",
        "DashBoard",
        "CustomersData",
>>>>>>> bd535f29bfedbd699035645919b0b1aac06857ed
    ),
];
