<?php

// autoload.php @generated by Composer

<<<<<<< HEAD
require_once __DIR__ . '/composer' . '/autoload_real.php';
=======
require_once __DIR__ . '/composer/autoload_real.php';
>>>>>>> 7f866eb5fc996b4b405e1f7e11d24ea4c67d71f6

return ComposerAutoloaderInita4a83323fa74f9ee3390af915b46a8f0::getLoader();
